### ISSUE TITLE
Update Wiki / Create & Update User Guide

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#219]
From the Comments on Steam it is clear that many users are missing a lot of understanding on how this mod works.

- [ ] Update the FAQ
- [ ] Create a Starter Guide (preferably on GitHub Wiki)
- [ ] Update Steam Page when the Guide is done. (Should be placed so that it is hard to miss)

The Guide should include Sections for the following Points
- [ ] Architect UI
- [ ] Research
- [ ] Detailed Info on all buildings (what do they do? How to use?) (should for example include that the blue zone is for a Recipe DB)
- [ ] Some Suggestion on how to automate XYZ

maybe more

**Comment by zymex22** [comment]
i have something planned for 2.5.0 to give players more introduction to certain things we get asked a lot about.
eq.
- Ai Workbench
- Where do i build...
- wheres is my stuff (grouped)
- basic how does this work?

I plan to add a popup to first PRF research that will give some basic info, further more i will add to some of the more advanced research where that technology demand some understanding.

I Hope that should create a better flow when playing so new players have easier way into the mod =)

Further more you are absolutely right we should update our Wiki also. but we just paused that a bit because of planned changes would need most pages a full rewrite.... so rather wait till we have a more or less stable full function version =)

Also after 2.5.0 i plant to update both Steam page =)

So To help learning it would be..
- Research popups with introduction to special parts of the mod
- Make sure all our Help button are updated and working
- Update Steam page
- Update Wiki

Are there other solutions to help new or old PRF players in better understanding how this mod works?

**Comment by zymex22** [comment]
### Introduction guide will go here:
https://github.com/zymex22/Project-RimFactory-Revived/wiki/1.-Intro-Guide

- **F.A.Q and Steam page** will be updated when 2.5.0 released with new look, links and FAQ regards everything working in 2.5.0 and old stuff removed.

- **Wiki detailed descriptions** for each item will properly be a running process.
but we have base done, and just need to go over them manually  

- **Help tabs** still need update and will properly be a running process too.  

- **Descriptions** need update and "flavour text" all around Exterien have started that job, but its a large one too.  

- i have **Already** implemented **Popup text** on most subjects when first research is done, 1 for each tier and then one for miners, assemblers, s.a.l and so on... where i give a brief introduction to each subject, i think that will be a good help for new players.
(i need to add a mod setting / patch to turn those off)

-

**Comment by zymex22** [comment]
work in progress but i have made a plan for it, and will implement over next period =) wiki will be last, but ill improve ingame and steam help first
