### ISSUE TITLE
Placeworker for T0 miner

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#290]
I need a special Placeworker for T0 miner to let it be place in a mountain wall instead of a normal wall.

right now i use nobos Placeworker for wall lamps (which only let it be placed in a wall)
```xml
    <placeWorkers>
      <li>ProjectRimFactory.AutoMachineTool.PlaceWorker_WallEmbedded</li>
    </placeWorkers>
```
https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/AutoMachineTool/PlaceWorker_WallEmbedded.cs 

but need a new one that instead of normal walls let it be placed on mauntain walls and/or smoothed walls...
Avatarfighter gave it a try but couldnt make it happen as he think it need a harmony patch or something?
and he dont know how to do those... =)

Can you @Sn1p3rr3c0n or @lilwhitemouse take a look?

**Comment by zymex22** [comment]
**Avatarfighter**
> To add onto this i think you need to use a harmony patch. My placeworker during testing worked but I couldnt for the life of me make it so that i could place a building ontop of a rock wall because the rock wall is considered a building

**Comment by Sn1p3rr3c0n** [comment]
I think a Harmony Patch is not required as a Test shows that it should be Possible
![image](https://user-images.githubusercontent.com/68663281/101980705-9429d680-3c67-11eb-8d6f-399c39c1cf51.png)

in this test i simply returned `AcceptanceReport.WasAccepted` in any case.
as you can see from the picture the placement is Possible.

**Comment by zymex22** [comment]
@Sn1p3rr3c0n if you can get it working, can you add a PR for it? we can show it to Avatarfighter so he can see it too, but guess no need to double work if you already got it working =)

**Comment by Sn1p3rr3c0n** [comment]
Initial version is done based upon `ProjectRimFactory.AutoMachineTool.PlaceWorker_WallEmbedded`

the new PlaceWorker can be used via `ProjectRimFactory.Common.PlaceWorker_NaturalWall`

**TODO**
- [ ] Consider the full building size instead of just the center _(see the right one)_
![image](https://user-images.githubusercontent.com/68663281/101984829-2c35b900-3c84-11eb-9bdd-e9854cb1a625.png)
_Left is just natural Wall. Middle is Smoothed Wall and Right is a example that only the center is evaluated ATM_

**Comment by zymex22** [comment]
lol didnt think about size :P but yea should probably consider size of building
