### ISSUE TITLE
Def's Missing in Save

### ISSUE THREAD

**Issue by AdamButtle15** [zymex22/Project-RimFactory-Revived#333]
All Previous structures are missing in architect tab and on map, I have the new additions like the mine shaft.
I have some Items, Mostly new ones though.

I have The details from Player.log and the readout from the debug menu

[Player.log](https://github.com/zymex22/Project-RimFactory-Revived/files/5752153/Player.log)
[Debug Log.txt](https://github.com/zymex22/Project-RimFactory-Revived/files/5752154/Debug.Log.txt)

**Comment by Sn1p3rr3c0n** [comment]
Old structures are no longer on the map due to the changes in the dev names. 
The Update (2.5.0) is not compatible with your old Save.
If you want to continue with your old stuff please use  https://steamcommunity.com/sharedfiles/filedetails/?id=2340838603

the things are not visible to you as DocWold needs to be updated
