### ISSUE TITLE
(Request)Darklight Wall Lamp

### ISSUE THREAD

**Issue by brucethemoose** [zymex22/Project-RimFactory-Revived#493]
**Is your feature request related to a problem? Please describe.**
There's no appropriate wall light for colonies with the Blindsight or Darkness Ideology Memes

**Describe the solution you'd like**
A darklight variant of the existing wall light. And possibly the other PRF lamps. 

**Describe alternatives you've considered**
Darklight wall lights from other mods. Unfortunately, the one I found is both less functional than the PRF wall lights and has a conflict with Vanilla Textures Expanded: Variations.

**Comment by zymex22** [comment]
I approve this, it can be done with a Patch for ideolgy.
I can look at this at a later point unless someone else wanna make it and create a PR for it.

**Comment by Sn1p3rr3c0n** [comment]
Darklight can now be easily be supported by adding `<darklightToggle>true</darklightToggle>` to the glower comp.

I noticed that we use `ProjectRimFactory.Misc.CompProperties_Glower_ColorPick` instead of `CompProperties_Glower`
Since a Color Picker is now built into the vanilla comp, I'm wondering if we should just drop `ProjectRimFactory.Misc.CompProperties_Glower_ColorPick`

_There is now even an bug with that class where the color can't be changed if used as a darklight_

**Comment by Sn1p3rr3c0n** [comment]
I switched to `CompProperties_Glower` in all cases where we allowed a wide range of colors and it would make sense to add Darklight.

`ProjectRimFactory.Misc.CompProperties_Glower_ColorPick` is still in use for Grow lights where i like the option to switch to a predefined Magenta _(as typically seen in grow lights)_. I find it unrealistic to allow any color for those.
