### ISSUE TITLE
Steam XML Patch Requests

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#576]
This issue will be used to keep track of some XML Patch request from Steam

> Is there a way to remove ores from the drill lists? I have a mod ("[Syulipia] Oriental Dragon Mod") that adds an ore which spawns a portal when mined and this desroyes the drills.
- [x] `[Syulipia] Oriental Dragon Mod` remove ore from drills

> Any way to create a patch for Dubs Skylight's, Glass+Lights and PRF's Glass?
- [x] [PRF Materials](https://github.com/zymex22/Project-RimFactory-Revived-Materials) Patch request

**Comment by InsanityPrelude** [comment]
I had a bit of time to kill, so I drafted up a fix for the Oriental Dragon Mod and submitted it as #591.

The PRF Materials / Skylights / Glass compact will be a bit more difficult, notably because Dubs Skylight's and Glass+Lights already have separate patches available as other mods which convert them both to use one type of glass or another.

**Comment by Sn1p3rr3c0n** [comment]
I Think for the Materials Patch we can just recommend them to use `Resource dictionary` by `Scorpio#1119` it is on Dubs Discord in the `customized-mods-and-modlists` Channel
