### ISSUE TITLE
 (Bug report) Assembler doesn't produce anything and can't be destroyed via developer mode

### ISSUE THREAD

**Issue by HSFpro** [zymex22/Project-RimFactory-Revived#604]
# Describe the bug
So I used **S.A.L. overclocked assembler mk. II** with the **Matterweaver from sparkling world mod**, it is stuck at 100% work. The bills is active, the material is nearby, the storage is set, yet nothing is produced by it
![image](https://user-images.githubusercontent.com/109332665/179160652-6c400bb2-91c2-4e75-9b4a-39c6360477ca.png)
It can't be deconstructed or destroyed even in developer mode
Here is my log https://gist.github.com/HugsLibRecordKeeper/470be2dc0620ba1f6dbe174b824b2c18
**To Reproduce**
Reproducibility: I don't know if it is happened on different workbenches or assemblers
1.  Construct Matterweaver and S.A.L. overclocked assembler mk. II
2.  Construct steel crate and set it to allow all
3.  Put a lot of steel on steel crate
4.  Add bill "Weave plasteel" and set it forever
5.  Wait the game autosave
6. Load it from autosave

The set up is similiar to this picture
![image](https://user-images.githubusercontent.com/109332665/179162668-eeeec660-6ab6-49e3-a39c-d3e048d9859d.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.3.3387
 - PRF Version: 2.6.6

**Comment by Sn1p3rr3c0n** [comment]
I am unable to reproduce your report.

According to the logs the following is the root cause for your issues
```
System.NullReferenceException: Object reference not set to an instance of an object
  at ProjectRimFactory.AutoMachineTool.SAL_TargetWorktable.CreateWorkingEffect
```

If you are truly on 2.6.6 then the only plausible cause would be that your bill has a `Null` recipe. 
That should never be the case, maybe your save is corrupt?

can you reproduce this issue on a fresh save?
If yes is that still true if you only use PRF and Sparkling Worlds?

**Comment by HSFpro** [comment]
It is indeed a save file corrupt.
I started it fresh with the mods below and made setup similar to what I mentioned on the report, after the game created autosave, i loaded it from the autosave, and the bug appeared

Mods:
- Id: brrainz.harmony
  Name: Harmony
- Id: ludeon.rimworld
  Name: Core
- Id: ludeon.rimworld.royalty
  Name: Royalty
- Id: ludeon.rimworld.ideology
  Name: Ideology
- Id: unlimitedhugs.hugslib
  Name: HugsLib
- Id: jecrell.jecstools
  Name: JecsTools
- Id: oskarpotocki.vanillafactionsexpanded.core
  Name: Vanilla Expanded Framework
- Id: spdskatr.projectrimfactory
  Name: Project RimFactory Revived
- Id: spdskatr.projectrimfactory.drones
  Name: Project RimFactory - Drones
- Id: albion.sparklingworlds.full
  Name: Sparkling Worlds - Full Mod
- Id: krkr.rocketman
  Name: RocketMan - Performance Mod
- Id: fluffy.modmanager
  Name: Mod Manager
- Id: ogre.ogrestack
  Name: OgreStack
- Id: vanillaexpanded.vfecore
  Name: Vanilla Furniture Expanded
- Id: vanillaexpanded.vfeproduction
  Name: Vanilla Furniture Expanded - Production
- Id: vanillaexpanded.vfepower
  Name: Vanilla Furniture Expanded - Power

**Comment by Sn1p3rr3c0n** [comment]
Thx for your report.
Can you please try and check if this issue is resolved when using the dll contained in the zip?
[ProjectRimFactory.zip](https://github.com/zymex22/Project-RimFactory-Revived/files/9120225/ProjectRimFactory.zip)

_Note: the dll won't solve existing cases but should prevent further cases._
_you can remove the sal by either loading a previous save or removing it from the save file (search for `ProjectRimFactory.AutoMachineTool.Building_AutoMachineTool`)_

**Comment by HSFpro** [comment]
Bug fixed, thx for your work @Sn1p3rr3c0n

**Comment by Sn1p3rr3c0n** [comment]
Issue might be caused by modded content
I did some test for #605 and found:

---
[issue604](https://github.com/zymex22/Project-RimFactory-Revived/tree/issue604) & Vanilla Helmet
https://gist.github.com/a4a2fd7bd0f4eabcbf21658921f6b400

[issue604](https://github.com/zymex22/Project-RimFactory-Revived/tree/issue604) & Modded Bench (sparklingworlds)
No issue

[master](https://github.com/zymex22/Project-RimFactory-Revived/tree/master) & Vanilla Helmet
no issue

[master](https://github.com/zymex22/Project-RimFactory-Revived/tree/master) & Modded Bench (sparklingworlds)
https://gist.github.com/06df83e8dce805450e3599969daf0a4b
