### ISSUE TITLE
 (Bug report) Disable and Priority

### ISSUE THREAD

**Issue by 849025143** [zymex22/Project-RimFactory-Revived#654]
# Describe the bug
Storage unit exception

**To Reproduce**
Reproducibility: ?
1. Disable steel storage
2. Allow other storage devices to store steel
3. If their priorities are the same, and there are "Adv I/O ports" and "I/O ports", a cycle will occur. [ pls check *.png ]

**Expected behavior**
Transfer steel from storage cell

**Actual Behavior**
Loop extraction and placement

**Screenshots**
![QQ截图20221120171828](https://user-images.githubusercontent.com/50692210/202903817-528acc5a-f692-4ede-ac5d-5a6ae25f93b5.png)

**Rimworld (please complete the following information):**
 - RimWorld Version: stam last
 - PRF Version: V2.7.5
 - Link to gist bug report: I didn't see the error report
 - Type: Storage exception
 - Severity: medium
 

**Modlist (please complete the following information):**
 - Does this problem exist if only prf is installed: yes
 - Your modlist (if needed): 
 - Do you know what mod conflicts?: idk

**Additional context**

**Comment by Sn1p3rr3c0n** [comment]
Please provide a **Clear** Description of your issue and steps to reproduce in text form.

You can start by introducing each building required for your issue to occur and how it is configured.
Then reuse the Name you gave them in your description so that i can follow it.

**Examples:**
_`DSU 1` Configured to store everything with Priority X_
_`DSU 2` Configured to store nothing with Priority X_
_`IO 1`  Configured as Input and linked with `DSU X`_
_`Advanced IO 1`  linked with `DSU X`_
_1. Disable Storage of X for  `DSU X`_
_2. Enable Storage of X for  `DSU X`_
_..._

**Comment by Sn1p3rr3c0n** [comment]
Closing due to lack of response from Reporter.
The Issue may be reopened if the Requested Information is Provided
