### ISSUE TITLE
Smart Recycler produces nothing when recycling apparel (Bug report)

### ISSUE THREAD

**Issue by jsokolic22** [zymex22/Project-RimFactory-Revived#788]
# Describe the bug
"Recycle Apparel" produces nothing when recycling apparel like for example parka, pants, tribal wear, hats ... etc.
Back in 1.4 it used to give some materials back while it was doing this job.
So there is no point in recycling when it is same as burning it witch is 10x faster using furnance.

**To Reproduce**
Reproducibility: ?
1. spawn any cloth item next to smart recycler and see that you wont get anything from it once job is done.
2. 
3. 

**Expected behavior**
It is expected to give some raw mats back.

**Actual Behavior**
nothing, job is done, nothing happens.

**Rimworld (please complete the following information):**
 - RimWorld Version: 1.5
 - PRF Version: IDK latest one.

**Comment by Sn1p3rr3c0n** [comment]
This Issue seems to be caused by a Change in `Verse.Thing:SmeltProducts`

in the past that could be used to get the Recourses for any item.
however for 1.5 that function was changed to only return for smeltable stuff

to fix this we either need a patch, or maybe a custom recipe.
Failing that we might need to redesign the buildings functionality

**Comment by jsokolic22** [comment]
After some more testing I found out that Recycler still works for "metalic" items, for example guns, swords, flak armor, etc... it is just that cloth/wood items give nothing after the process is done... so Recycler is still very much usable machine.

**Comment by Sn1p3rr3c0n** [comment]
yes with the changes by Ludeon only Smeltable things (such as metals) work at the moment.
We will look into fixes
